services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: kafka-test-zookeeper-1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-persistence:/bitnami

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-test-kafka-1
    volumes:
      - kafka-persistence:/bitnami/kafka
      - ./kafka-server.properties:/bitnami/kafka/config/server.properties:ro
    environment:
#      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
##      KAFKA_LISTENERS: PLAINTEXT://:9092
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_HEAP_OPTS: "-Xmx350M -Xms350M"
      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_CFG_NODE_ID: 0
#      KAFKA_CFG_PROCESS_ROLES: controller,broker
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    depends_on:
      - zookeeper

  kafka-setup:
    image: bitnami/kafka:latest
    depends_on:
      - kafka

  kafka-producer:
    image: bitnami/kafka:latest
    command:
      - bash
      - -c
      - while true; do echo "Message at $(date)"; sleep 0.001; done | exec kafka-console-producer.sh --timeout 1000 --topic test-topic --bootstrap-server kafka:9092
    depends_on:
      - kafka

  kafka-consumer:
    image: bitnami/kafka:latest
    command: kafka-console-consumer.sh --timeout-ms 300000 --topic test-topic --bootstrap-server kafka:9092 --group test-consumer-group --property print.partition=true --consumer-property partition.assignment.strategy=org.apache.kafka.clients.consumer.RangeAssignor --consumer-property rebalance.timeout.ms=4200 --consumer-property session.timeout.ms=3500 --consumer-property max.poll.interval.ms=3800
    depends_on:
      - kafka

volumes:
  zookeeper-persistence:
    driver: local
    name: zookeeper-persistence
  kafka-persistence:
    driver: local
    name: kafka-persistence
